<?php

namespace ProcessWire;

/**
 * ProcessWire FloatRange Inputfield
 * By @eelkenet, https://eelke.net
 */

class FieldtypeFloatRange extends FieldtypeFloat
{

	public static function getModuleInfo()
	{
		return array(
			'title' => __('Float (Range)', __FILE__),
			'summary' => __('Fieldtype for the range slider inputfield', __FILE__), // Module Summary
			'permanent' => false,
			'version' => 003,
			'icon' => 'sliders',
			'href' => 'https://github.com/eelke/InputfieldFloatRange',
			'author' => 'Eelke Feenstra, eelke.net',
			'requires' => ["InputfieldFloatRange", "ProcessWire>=3.0.83"],
		);
	}

	public function getInputfield(Page $page, Field $field)
	{
		$inputfield = $this->modules->get('InputfieldFloatRange');
		$inputfield->class = $this->className();
		$inputfield->precision = $field->precision;
		return $inputfield;
	}
}
